// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPuHLJk0YE9-T2-daoNP-CMCxg9lE3r4',
    appId: '1:1055313647379:web:0e5481f9d025ba5ed5ece6',
    messagingSenderId: '1055313647379',
    projectId: 'moblelab-flutter-firebase',
    authDomain: 'moblelab-flutter-firebase.firebaseapp.com',
    storageBucket: 'moblelab-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-62d1DFB2wUpn0bpqMvW7tfxxelhhwQ',
    appId: '1:1055313647379:android:92dd952301bfdf56d5ece6',
    messagingSenderId: '1055313647379',
    projectId: 'moblelab-flutter-firebase',
    storageBucket: 'moblelab-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhaofa_LX-OPkM4CGJQIkKCLrE0Ihf_sY',
    appId: '1:1055313647379:ios:a5506b21032659cad5ece6',
    messagingSenderId: '1055313647379',
    projectId: 'moblelab-flutter-firebase',
    storageBucket: 'moblelab-flutter-firebase.appspot.com',
    iosClientId:
        '1055313647379-cqrk7bv2soo9aq76mb20nbeie2mb12el.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhaofa_LX-OPkM4CGJQIkKCLrE0Ihf_sY',
    appId: '1:1055313647379:ios:a5506b21032659cad5ece6',
    messagingSenderId: '1055313647379',
    projectId: 'moblelab-flutter-firebase',
    storageBucket: 'moblelab-flutter-firebase.appspot.com',
    iosClientId:
        '1055313647379-cqrk7bv2soo9aq76mb20nbeie2mb12el.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
